INVENTORY_ITEMS = [
    {
        "id": 1, 
        "name": "SonicWave Pro Wireless Bluetooth Headphones", 
        "brand": "AudioTech",
        "model": "SW-Pro-2024",
        "price": 79.99, 
        "stock": 25,
        "category": "Audio",
        "description": "Premium wireless Bluetooth headphones featuring active noise cancellation, ergonomic over-ear design, and superior sound quality. Perfect for music, calls, and gaming.",
        "specifications": {
            "batteryLife": "30 hours with ANC off, 24 hours with ANC on",
            "bluetoothVersion": "5.3",
            "drivers": "40mm dynamic drivers",
            "frequency": "20Hz - 20kHz",
            "chargingTime": "2 hours (USB-C fast charging)",
            "weight": "280g",
            "foldable": True,
            "microphoneType": "Built-in omnidirectional"
        },
        "features": [
            "Active Noise Cancellation",
            "Ergonomic over-ear design", 
            "Touch controls",
            "Voice assistant compatible",
            "Multi-device pairing",
            "Quick charge (15 min = 3 hours playback)"
        ],
        "colors": ["Midnight Black", "Pearl White", "Rose Gold"],
        "warranty": "2 years manufacturer warranty",
        "rating": 4.2,
        "review_count": 127,
        "top_review": "Excellent battery life and comfortable fit. Great value for money at $79.99. ANC works surprisingly well for this price point."
    },
    {
        "id": 2, 
        "name": "TechGuard Pro iPhone Case", 
        "brand": "TechGuard",
        "model": "TG-iPhone-Pro-2024",
        "price": 24.99, 
        "stock": 50,
        "category": "Mobile Accessories",
        "description": "Military-grade drop protection case with wireless charging compatibility and premium materials.",
        "specifications": {
            "dropProtection": "15 feet military standard",
            "materials": "TPU + Polycarbonate",
            "wirelessCharging": True,
            "screenLipProtection": "1.2mm raised edges",
            "cameraProtection": "2mm raised lens protection"
        },
        "features": [
            "Military-grade drop protection",
            "Wireless charging compatible",
            "Precise cutouts",
            "Anti-slip grip texture",
            "Screen and camera protection"
        ],
        "compatibility": ["iPhone 15", "iPhone 15 Pro", "iPhone 14", "iPhone 14 Pro"],
        "colors": ["Clear", "Black", "Navy Blue", "Rose Gold"],
        "warranty": "1 year replacement warranty",
        "rating": 4.5,
        "review_count": 89,
        "top_review": "Perfect fit and excellent protection. Dropped my phone multiple times and no damage. Wireless charging works flawlessly."
    },
    {
        "id": 3, 
        "name": "PowerFlow USB-C Charging Cable", 
        "brand": "PowerFlow",
        "model": "PF-USBC-3M-2024",
        "price": 1.99, 
        "stock": 100,
        "category": "Cables & Adapters",
        "description": "High-speed USB-C to USB-C cable with 100W power delivery and 480Mbps data transfer. Durable braided design.",
        "specifications": {
            "length": "3 meters (10 feet)",
            "powerDelivery": "100W fast charging",
            "dataTransfer": "480Mbps",
            "durability": "25,000+ bend cycles",
            "connector": "USB-C to USB-C"
        },
        "features": [
            "100W fast charging support",
            "High-speed data transfer",
            "Braided nylon exterior",
            "Reinforced connectors",
            "Universal compatibility"
        ],
        "compatibility": ["MacBook", "iPad Pro", "Android phones", "Nintendo Switch", "Steam Deck"],
        "colors": ["Space Gray", "Silver", "Blue"],
        "warranty": "2 years manufacturer warranty",
        "rating": 4.7,
        "review_count": 203,
        "top_review": "Excellent build quality and fast charging speeds. The 3-meter length is perfect for my setup. Highly recommended!"
    },
    {
        "id": 4, 
        "name": "PowerVault Portable Power Bank 10000mAh", 
        "brand": "PowerVault",
        "model": "PV-10K-Pro-2024",
        "price": 34.99, 
        "stock": 30,
        "category": "Power & Charging",
        "description": "Compact 10000mAh power bank with 22.5W fast charging, wireless charging pad, and digital display.",
        "specifications": {
            "capacity": "10000mAh (37Wh)",
            "fastCharging": "22.5W USB-C PD",
            "wirelessCharging": "15W Qi wireless",
            "display": "LED digital percentage display",
            "inputPorts": "USB-C",
            "outputPorts": "USB-C, USB-A, Wireless pad",
            "weight": "220g",
            "dimensions": "147 x 69 x 16mm"
        },
        "features": [
            "22.5W fast charging",
            "15W wireless charging pad",
            "Digital battery percentage display",
            "Multiple device charging",
            "Pass-through charging",
            "Safety protection circuits"
        ],
        "batteryLife": "2-3 full smartphone charges",
        "colors": ["Black", "White", "Blue"],
        "warranty": "18 months manufacturer warranty",
        "rating": 4.4,
        "review_count": 156,
        "top_review": "Love the wireless charging feature and digital display. Fast charging works great and the compact size is perfect for travel."
    },
    {
        "id": 5, 
        "name": "BoomBox Elite Bluetooth Speaker", 
        "brand": "BoomBox",
        "model": "BB-Elite-360-2024",
        "price": 59.99, 
        "stock": 15,
        "category": "Audio",
        "description": "360-degree sound Bluetooth speaker with deep bass, waterproof design, and 24-hour battery life.",
        "specifications": {
            "batteryLife": "24 hours continuous playback",
            "bluetoothVersion": "5.3",
            "range": "100 feet",
            "waterproof": "IPX7 rated",
            "drivers": "Dual 10W drivers + passive radiator",
            "frequency": "60Hz - 20kHz",
            "chargingTime": "3 hours USB-C",
            "weight": "580g"
        },
        "features": [
            "360-degree surround sound",
            "IPX7 waterproof rating",
            "24-hour battery life",
            "Built-in microphone for calls",
            "Party Connect (link multiple speakers)",
            "Voice assistant compatible"
        ],
        "colors": ["Midnight Black", "Ocean Blue", "Forest Green"],
        "warranty": "1 year manufacturer warranty",
        "rating": 4.3,
        "review_count": 78,
        "top_review": "Amazing sound quality for the price. The 360-degree audio really makes a difference. Waterproof feature is great for pool parties."
    },
    {
        "id": 6, 
        "name": "ErgoDesk Aluminum Laptop Stand", 
        "brand": "ErgoDesk",
        "model": "ED-Alu-Pro-2024",
        "price": 45.99, 
        "stock": 20,
        "category": "Computer Accessories",
        "description": "Premium aluminum laptop stand with adjustable height and angle, heat dissipation design, and universal compatibility.",
        "specifications": {
            "material": "Premium aluminum alloy",
            "adjustability": "6-level height, 360° rotation",
            "compatibility": "10-17 inch laptops",
            "weightCapacity": "15kg (33 lbs)",
            "dimensions": "260 x 230 x 150mm",
            "weight": "1.2kg",
            "foldable": True
        },
        "features": [
            "Ergonomic viewing angle",
            "Heat dissipation design",
            "Anti-slip silicone pads",
            "Foldable and portable",
            "Cable management",
            "Stable triangular structure"
        ],
        "colors": ["Space Gray", "Silver"],
        "warranty": "3 years manufacturer warranty",
        "rating": 4.6,
        "review_count": 92,
        "top_review": "Solid build quality and perfect for ergonomic setup. My MacBook runs cooler and my neck feels much better after long work sessions."
    },
    {
        "id": 7, 
        "name": "ClickPro Wireless Mouse", 
        "brand": "ClickPro",
        "model": "CP-Wireless-Pro-2024",
        "price": 29.99, 
        "stock": 40,
        "category": "Computer Accessories",
        "description": "Precision wireless mouse with ergonomic design, adjustable DPI, and long-lasting battery.",
        "specifications": {
            "sensor": "Optical precision sensor",
            "dpi": "800-3200 DPI adjustable",
            "batteryLife": "18 months (2 AA batteries)",
            "connectivity": "2.4GHz wireless + USB-C receiver",
            "range": "33 feet",
            "buttons": "6 programmable buttons",
            "weight": "85g (without batteries)"
        },
        "features": [
            "Ergonomic right-hand design",
            "Adjustable DPI settings",
            "Silent click technology",
            "Programmable buttons",
            "Nano USB receiver storage",
            "Auto sleep mode"
        ],
        "compatibility": ["Windows", "macOS", "Linux", "Chrome OS"],
        "colors": ["Black", "White", "Blue"],
        "warranty": "1 year manufacturer warranty",
        "rating": 4.1,
        "review_count": 134,
        "top_review": "Comfortable grip and accurate tracking. Silent clicks are great for office use. Battery life is impressive."
    },
    {
        "id": 8, 
        "name": "ShieldMax Tempered Glass Screen Protector", 
        "brand": "ShieldMax",
        "model": "SM-TG-9H-2024",
        "price": 9.99, 
        "stock": 75,
        "category": "Mobile Accessories",
        "description": "Premium 9H hardness tempered glass screen protector with oleophobic coating and bubble-free installation.",
        "specifications": {
            "hardness": "9H tempered glass",
            "thickness": "0.33mm ultra-thin",
            "transparency": "99.9% HD clarity",
            "coating": "Oleophobic anti-fingerprint",
            "cutouts": "Precise speaker and camera cutouts",
            "installation": "Bubble-free alignment tool included"
        },
        "features": [
            "9H scratch resistance",
            "Anti-fingerprint coating",
            "Case-friendly design",
            "Bubble-free installation",
            "Edge-to-edge protection",
            "Shatter-proof safety film"
        ],
        "compatibility": ["iPhone 15 series", "Samsung Galaxy S24 series", "Google Pixel 8 series"],
        "package": "2-pack with installation kit",
        "warranty": "Lifetime replacement guarantee",
        "rating": 4.5,
        "review_count": 267,
        "top_review": "Easy installation and perfect clarity. No bubbles and feels just like the original screen. Great value for a 2-pack."
    },
    {
        "id": 9, 
        "name": "GripMount Pro Car Phone Mount", 
        "brand": "GripMount",
        "model": "GM-Pro-Mag-2024",
        "price": 19.99, 
        "stock": 35,
        "category": "Mobile Accessories",
        "description": "Magnetic car phone mount with 360-degree rotation, strong hold, and dashboard/vent mounting options.",
        "specifications": {
            "magnetStrength": "N52 neodymium magnets",
            "rotation": "360-degree rotation",
            "tilt": "45-degree adjustable tilt",
            "mounting": "Dashboard + air vent options",
            "compatibility": "4-7 inch phones with magnetic plates",
            "weight": "120g"
        },
        "features": [
            "Ultra-strong magnetic hold",
            "One-hand operation",
            "360-degree rotation",
            "Dual mounting options",
            "Cable management",
            "Non-slip base pad"
        ],
        "package": "Includes 4 magnetic plates (2 round, 2 rectangular)",
        "colors": ["Black", "Silver"],
        "warranty": "2 years manufacturer warranty",
        "rating": 4.3,
        "review_count": 145,
        "top_review": "Strong magnetic hold and easy one-handed use. Perfect for GPS navigation. The dual mounting options are very convenient."
    },
    {
        "id": 10, 
        "name": "GameMaster RGB Gaming Keyboard", 
        "brand": "GameMaster",
        "model": "GM-RGB-Mech-2024",
        "price": 89.99, 
        "stock": 12,
        "category": "Gaming",
        "description": "Mechanical gaming keyboard with RGB backlighting, hot-swappable switches, and programmable macros.",
        "specifications": {
            "switches": "Hot-swappable mechanical blue switches",
            "backlighting": "Per-key RGB (16.8M colors)",
            "layout": "Tenkeyless (87 keys)",
            "connectivity": "USB-C detachable cable",
            "polling": "1000Hz polling rate",
            "macros": "Full programmability",
            "keycaps": "Double-shot PBT keycaps"
        },
        "features": [
            "Hot-swappable mechanical switches",
            "Per-key RGB customization",
            "N-key rollover",
            "Dedicated media controls",
            "Programmable macros",
            "Gaming mode (disable Windows key)",
            "Detachable USB-C cable"
        ],
        "software": "GameMaster Pro software included",
        "colors": ["Black frame with RGB"],
        "warranty": "2 years manufacturer warranty",
        "rating": 4.7,
        "review_count": 89,
        "top_review": "Excellent build quality and the hot-swappable switches are a game changer. RGB effects are stunning and software is intuitive."
    }
]